name: Auto Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a sentim-analysis
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/sentim-analysis.git HEAD:main --force
